FROM node:24-bookworm-slim AS builder
WORKDIR /app
ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0 NEXT_TELEMETRY_DISABLED=1
RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

ARG MONGODB_URI
ARG REDIS_URL
ARG REALTIME_URL
ARG REALTIME_SECRET
ARG BETTER_AUTH_SECRET
ARG BETTER_AUTH_URL
ARG ROOM_SIGNING_SECRET
ARG AUTH_GOOGLE_ID
ARG AUTH_GOOGLE_SECRET
ARG AUTH_DISCORD_ID
ARG AUTH_DISCORD_SECRET
ARG BREVO_API_KEY
ARG RESEND_API_KEY
ARG ADMIN_TOKEN
ARG WCA_CLIENT_ID
ARG WCA_CLIENT_SECRET
ARG FILES_EMULATOR
ARG FILES_BUCKET
ARG FILES_ACCESS_KEY_ID
ARG FILES_SECRET_ACCESS_KEY
ARG FILES_ENDPOINT
ARG FILES_PUBLIC_BASE_URL
ARG FILES_REGION
ARG GITHUB_APP_ID
ARG GITHUB_APP_PRIVATE_KEY
ARG GITHUB_APP_INSTALLATION_ID
ARG GITHUB_REPO
ARG MEILISEARCH_HOST
ARG MEILISEARCH_API_KEY
ARG NEXT_PUBLIC_FIREBASE_EMULATOR
ARG NEXT_PUBLIC_PROJECT_ID
ARG NEXT_PUBLIC_REALTIME
ARG NEXT_PUBLIC_API_KEY
ARG NEXT_PUBLIC_AUTH_DOMAIN
ARG NEXT_PUBLIC_STORAGE_BUCKET
ARG NEXT_PUBLIC_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_APP_ID
ARG NEXT_PUBLIC_DISCORD_CLIENT_ID

RUN pnpm build && rm -rf .next/cache

FROM node:24-bookworm-slim
WORKDIR /app
ENV NODE_ENV=production NEXT_TELEMETRY_DISABLED=1 PORT=8000
COPY --from=builder /app ./
EXPOSE 8000
CMD ["node", "node_modules/next/dist/bin/next", "start"]
