import { CubeCollection } from "@/interfaces/cubeCollection";

export const cubeCollection: CubeCollection[] = [
  {
    event: "222",
    id: 1,
    name: "2x2",
    src: "/categories/cube222.svg",
    displayId: "2x2x2",
  },
  {
    event: "333",
    id: 2,
    name: "3x3",
    src: "/categories/cube333.svg",
    displayId: "3x3x3",
  },
  {
    event: "333",
    id: 3,
    name: "3x3 OH",
    src: "/categories/cube333oh.svg",
    displayId: "3x3x3",
  },
  {
    event: "444",
    id: 4,
    name: "4x4",
    src: "/categories/cube444.svg",
    displayId: "4x4x4",
  },
  {
    event: "555",
    id: 5,
    name: "5x5",
    src: "/categories/cube555.svg",
    displayId: "5x5x5",
  },
  {
    event: "666",
    id: 6,
    name: "6x6",
    src: "/categories/cube666.svg",
    displayId: "6x6x6",
  },
  {
    event: "777",
    id: 7,
    name: "7x7",
    src: "/categories/cube777.svg",
    displayId: "7x7x7",
  },
  {
    event: "sq1",
    id: 8,
    name: "SQ1",
    src: "/categories/cubesq1.svg",
    displayId: "square1",
  },
  {
    event: "skewb",
    id: 9,
    name: "Skewb",
    src: "/categories/skewb.svg",
    displayId: "skewb",
  },
  {
    event: "pyram",
    id: 10,
    name: "Pyraminx",
    src: "/categories/pyraminx.svg",
    displayId: "pyraminx",
  },
  {
    event: "minx",
    id: 11,
    name: "Megaminx",
    src: "/categories/minx.svg",
    displayId: "megaminx",
  },
];
