import { TRAINER_PAGE_SIZE, TRAINER_RECENT_TIMES_WINDOW, TRAINER_TARGET_OPTIONS } from '@nexustimer/contracts'

export const TRAINER_DEFAULT_SLUG = 'oll'
export const TRAINER_DEFAULT_TARGET_SECONDS = 2
export const TRAINER_RECENT_WINDOW = TRAINER_RECENT_TIMES_WINDOW
export { TRAINER_PAGE_SIZE, TRAINER_TARGET_OPTIONS }
