import { test, expect } from '@playwright/test'

test('Should create and delete a cube collection, also validate delete form', async ({ page }) => {
  await page.goto('http://localhost:3000/cubes')
  await page.getByTestId('empty-cubes-container').getByRole('button', { name: 'New collection' }).click()
  await page.getByTestId('drawer-input-name').click()
  await page.getByTestId('drawer-input-name').press('CapsLock')
  await page.getByTestId('drawer-input-name').fill('T')
  await page.getByTestId('drawer-input-name').press('CapsLock')
  await page.getByTestId('drawer-input-name').fill('Test')
  await page.getByTestId('drawer-input-name').press('CapsLock')
  await page.getByTestId('drawer-input-name').fill('TestC')
  await page.getByTestId('drawer-input-name').press('CapsLock')
  await page.getByTestId('drawer-input-name').fill('TestCube')
  await page.getByTestId('drawer-accept-button').click()
  await expect(
    page
      .locator('div')
      .filter({ hasText: /^TestCube$/ })
      .first()
  ).toBeVisible()
  await page.getByRole('button', { name: 'Delete' }).click()
  await expect(page.getByTestId('dialog-delete-cube-description')).toBeVisible()
  await page.getByTestId('dialog-delete-cube-input').click()
  await page.getByTestId('dialog-delete-cube-input').fill('asd')
  await page.getByTestId('dialog-delete-cube-accept-button').click()
  await expect(page.getByTestId('dialog-delete-cube-error-message')).toBeVisible()
  await page.getByTestId('dialog-delete-cube-input').click()
  await page.getByTestId('dialog-delete-cube-input').fill('')
  await page.getByTestId('dialog-delete-cube-input').press('CapsLock')
  await page.getByTestId('dialog-delete-cube-input').fill('T')
  await page.getByTestId('dialog-delete-cube-input').press('CapsLock')
  await page.getByTestId('dialog-delete-cube-input').fill('Test')
  await page.getByTestId('dialog-delete-cube-input').press('CapsLock')
  await page.getByTestId('dialog-delete-cube-input').fill('TestC')
  await page.getByTestId('dialog-delete-cube-input').press('CapsLock')
  await page.getByTestId('dialog-delete-cube-input').fill('TestCube')
  await page.getByTestId('dialog-delete-cube-accept-button').click()
  await expect(page.getByText('Collection deleted')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'No cubes for display.' })).toBeVisible()
})
