import { RoomType } from '@/enums/RoomType';
import { RoomStatus } from '@/enums/RoomStatus';
import { PlayerStatus } from '@/enums/PlayerStatus';

export interface Room {
  // generated by form
  id: string;
  path: string;
  name: string;
  event: string;
  type: RoomType;
  password?: string;
  maxRoundTime: number;
  totalRounds: number;
  createdAt: number;
  status: RoomStatus;
  owner: string;

  // generated by the system
  roundsFinalizationTimes?: number[];
  matchFinalizationTime?: number;
  preparationFinalizationTime?: number;

  // game state
  presence: {
    [userId: string]: {
      solves: number[];
      status: PlayerStatus;
      lastUpdated?: number;
      joinedAt?: number;
      name?: string;
      image?: string;
    };
  }
}
