import { RoomType } from '@/enums/RoomType';
import { RoomStatus } from '@/enums/RoomStatus';
import { PlayerPresence } from '@/interfaces/PlayerPresence';

export interface Room {
  // generated by form
  id: string;
  path: string;
  name: string;
  event: string;
  type: RoomType;
  password?: string;
  maxRoundTime: number;
  totalRounds: number;
  createdAt: number;
  status: RoomStatus;
  createdBy: string;
  authority: {
    leaderId: string | null
    leaseExpireAt: number
    term: number
  }

  // generated by the system
  roundsFinalizationTimes?: number[];
  matchFinalizationTime?: number;
  preparationFinalizationTime?: number;

  // game state
  presence: {
    [userId: string]: PlayerPresence
  }
}


